"""empty message

Revision ID: bb984d8477e7
Revises: 6da83eec3f47
Create Date: 2016-04-26 21:06:21.694790

"""

# revision identifiers, used by Alembic.
revision = 'bb984d8477e7'
down_revision = '6da83eec3f47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('category', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'category')
    ### end Alembic commands ###
