"""empty message

Revision ID: cb8900e7424c
Revises: 7e40d7c825f8
Create Date: 2016-04-19 06:04:16.729381

"""

# revision identifiers, used by Alembic.
revision = 'cb8900e7424c'
down_revision = '7e40d7c825f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('thumbnail', sa.String(length=255), nullable=True))
    op.drop_column('wishes', 'origin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('origin', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('wishes', 'thumbnail')
    ### end Alembic commands ###
